services:
  hshn_security_voter_extra.class_matcher.provider_matcher.def:
    abstract: true
    class: Hshn\SecurityVoterExtraBundle\ClassMatcher\ProviderMatcher
    arguments: [@hshn_class_matcher.matcher_provider]


