services:
  hshn_security_voter_generator.class_matcher.provider_matcher.def:
    abstract: true
    class: Hshn\SecurityVoterGeneratorBundle\ClassMatcher\ProviderMatcher
    arguments: [@hshn_class_matcher.matcher_provider]


